### ISSUE TITLE
list to json from response object

### ISSUE THREAD

**Issue by serialbandicoot** [Finnhub-Stock-API/finnhub-python#2]
HI this is a bit of a newbie question. 

```python
@app.route('/fn_earnings')
def finnhub_earnings():
    response = fc.company_earnings('TSLA', limit=5)
    return { 'data': response }
```

I'm trying to return the response object from a flask query as json. I've tried multiple combinations but I can't seem to figure out the solution. All the examples are using print.

Would you please be able to give me some idea of how to coerce the object into an json format. 

Many thanks...

**Comment by finnhubio** [comment]
Have you tried  response.to_dict() ?

**Comment by serialbandicoot** [comment]
Yeah it does work, however I thought the library was more of a wrapper and therefore I would be able to get back a json object a bit easier. 

I've had a look at the JS version and this seems to be easier to get a json response out. So I might switch or use fhub as this also has a json option, without the need to dig.

**Comment by finnhubio** [comment]
@nongdenchet can you help take a look whether it's possible to support JSON conversion for these cases ?

**Comment by finnhubio** [comment]
This feature is now supported right out of the box. All data is returned in JSON format from 2.0
