### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by Sinansi** [Finnhub-Stock-API/finnhub-python#21]
Hello, 

For the following example, how did you format the dates in the 'from' 'to' arguments like this?

# Stock candles
res = finnhub_client.stock_candles('AAPL', 'D', 1590988249, 1591852249)
print(res)

Thank you!

**Comment by aditya08** [comment]
the 'from' and 'to' arguments are in UNIX timestamp format. 

For example, you can use the Python `datetime` package to generate UNIX timestamps:
`from datetime import datetime`
`timestamp = datetime.timestamp(datetime.now())`
`print(timestamp)`

**Comment by Sinansi** [comment]
Thank you!
