### ISSUE TITLE
finnhub_client.etfs_ind_exp(...) returns holdings, not industry exposure

### ISSUE THREAD

**Issue by layoutanalysis** [Finnhub-Stock-API/finnhub-python#28]
Check https://github.com/Finnhub-Stock-API/finnhubpython/blob/2c38c0c65264475ffea0de6913062202a969ade3/finnhub/client.py#L342
```
    def etfs_ind_exp(self, symbol):
        return self._get("/etf/holdings", params={"symbol": symbol})
```

**Comment by finnhubio** [comment]
This has been fixed in our recent release. Apologies for the inconvenience.
