### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by digicom1978** [Finnhub-Stock-API/finnhub-python#29]
Hi,
I am using python version of finnhub. And trying to get financial data from financials_reported api, but for some companies, data looks missing. 

For example, PFE, this api returns data for 8 years. (No recent data, from 2011 to 2018).
It has 8 years of Cash Flow data, but 7 years of Income Statement and 1 year of Balance Sheet. I don't know why there is these difference between CF, IC and BS?

Please take a look at this gap.
Regards,

**Comment by finnhubio** [comment]
Hi, the issue has been corrected. Can you please try again ?
