### ISSUE TITLE
No attribute called configuration

### ISSUE THREAD

**Issue by benediktbluemelhuber** [Finnhub-Stock-API/finnhub-python#4]
Hello, i get an error when I try to initialize my api Key. What am I doung wrong?

`configuration = finnhub.Configuration(
    api_key={
        'token': 'brv2v2frh5r9k3fgpqug'
    }
)`

Error that I get is: AttributeError: 'module' object has no attribute 'Configuration'

**Comment by finnhubio** [comment]
Is your python file named finnhub.py ?

**Comment by benediktbluemelhuber** [comment]
Yes it‘s called finnhub.py

Von meinem iPhone gesendet

**Comment by finnhubio** [comment]
You can't name a file using the same name with the library. It will cause confusion as in this case. Try changing it to another name

**Comment by nickrflynn** [comment]
I did the same thing 🤦

**Comment by nongdenchet** [comment]
I am closing this issue now
