### ISSUE TITLE
Permissions required for using API?

### ISSUE THREAD

**Issue by gmehta1996** [Finnhub-Stock-API/finnhub-python#6]
Do we require any kind of permissions if we use these APIs in an office project.
Suppose if I need to get data from bse /nse or nyse on a daily basis for just viewing the current values of a company.
So can this be used for such  an office project or would we require any legal permissions????

**Comment by nongdenchet** [comment]
@finnhubio can you have a look into this question?

**Comment by finnhubio** [comment]
Hi there, you need to obtain a commercial license to use it inside your company. Please send us an email at support@finnhub.io to discuss the license.
