### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'B616C79'

### ISSUE THREAD

**Issue by garrrikkotua** [Finnhub-Stock-API/finnhub-python#8]
When calling method 'company_profile()' for symbols 'SFIX' and 'TSLA' (possibly there are more) I get this: _ValueError: invalid literal for int() with base 10: 'B616C79'._ However, when I use the same method with simple get request everything works fine.

**Comment by nongdenchet** [comment]
@finnhubio can you have a look into this issue?

**Comment by finnhubio** [comment]
> When calling method 'company_profile()' for symbols 'SFIX' and 'TSLA' (possibly there are more) I get this: _ValueError: invalid literal for int() with base 10: 'B616C79'._ However, when I use the same method with simple get request everything works fine.

This should be fixed in the latest version 2.0. Can you try to remove and install the library again to get the latest version ?

**Comment by nongdenchet** [comment]
closing for now since there is not response, feel free to reopen it if the issue still happens to you
